server:
    port: 7002

mysql:
    host: 127.0.0.1
    port: 3306
    database: gin_demo
    username: gin_demo
    password: gin_demo
    charset: utf8mb4
    loc: Asia/Shanghai

redis:
    addr: 47.120.71.181:6379
    password: foobared
